### ISSUE TITLE
Forced Host motds not displaying correctly for bedrock clients

### ISSUE THREAD

**Issue by ryan77627** [yesdog/Waterdog#107]
**Version of Waterdog**
git:Waterdog-Bootstrap:1.15-SNAPSHOT:a556bfd:308 by md_5

**Expected Behavior**
When adding a server with a forced_host url rather than the main url, the motd should reflect that of its associated server's motd entry

**Actual Behavior**
When entering the url of a forced_host, the motd for the main proxy shows but the connection still works like expected.

**Describe the bug**
Wrong motd shows for a forced_host entry on bedrock, even though ping_passthrough is false. Works as expected for java clients. I have two listeners setup, one for java and one for bedrock using raknet. The java motds display as intended, however the bedrock motds always display as the proxy's main motd

**To Reproduce**
1. Setup Waterdog to have a motd of 'Example 1'
1. Setup a forced_host "subdomain1.example.com' to associate with server "subdomain1"
1. Setup server "subdomain1" to have a motd of 'Example 2'
1. Add a server to Minecraft bedrock pointing to "subdomain1.example.com" and its motd will be 'Example 1' rather than 'Example 2'

**Screenshots**

None, can provide if needed.

**Server software used:**
Waterdog pointing to GeyserMC instance

**Comment by Alemiz112** [comment]
Hello, if you mean MOTD shown in server list window, that this is impossible. Im MCBE we can not determine which forced host will client use when he connects. This is because we need to receive packet information which tells us right forced host.

If you mean wrong MOTD in player list window after player joins game, I can look on it. Right now, I think MOTD of first server is displayed there.
