### ISSUE TITLE
Food bar bug in Nukkit

### ISSUE THREAD

**Issue by AlicanCopur** [yesdog/Waterdog#144]
**Version of Waterdog**

git:Waterdog-Bootstrap:1.15-SNAPSHOT:97da972:25 by md_5

**Expected Behavior**

Food bar works normally

**Actual Behavior**

When you exhaust, food bar is bugging and always cleaning and filling.

**Crashdump, Backtrace or Other Files**

**Describe the bug**

Join a Nukkit server with Waterdog proxy, exhaust (sprint, jump and your food bar will decrease) and bugging.

**Screenshots**

**Server software used:**

Nukkit

**Additional context**

**Comment by Alemiz112** [comment]
Hi, this bug happens randomly, but I can confirm it.

Some more info:
- Happens on some "wrong" nukkit main worlds only (further "wrong nukkit")
- Happens if "wrong nukkit" is the first server joined by player
- If you transfer from pmmp to "wrong nukkit" it does not happen
- It is caused by how nukkit implements entity food attributes (does happen with Nemisys proxy too)

Basically It happens randomly on server instance. Wiping out and generating new world fixes this, usually.
I can not help much here. I have already tried to fix this bug.

**Comment by AlicanCopur** [comment]
What do you mean "wrong nukkit"? I have HUB (SkyBlock + MiniGames) server, HUB is PMMP, MiniGames is PMMP and SkyBlock is Nukkit. Food bar bugs when I transfer from Hub to SkyBlock.

**Comment by Alemiz112** [comment]
It seems like client doesnt like to have different difficulties per server. If it is required, you can send new difficulty right after player joins new server.
