### ISSUE TITLE
UPDATE MC:BE 1.16

### ISSUE THREAD

**Issue by xJuqnPvP** [yesdog/Waterdog#147]
I would like to know if you could update the proxy to the new versions of MCBE

**Comment by Alemiz112** [comment]
The Waterdog is already updated to latest MCBE version. Official builds are not compiled successfully due to missing permissions to edit build configs. You can download latest working build from my [Jenkins server](https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/). Use branch `alemiz-zlib` for official build.

**Comment by xJuqnPvP** [comment]
Thanks!
