### ISSUE TITLE
Support multi protocol [Waterdog PE]

### ISSUE THREAD

**Issue by JuqnDeveloper** [yesdog/Waterdog#179]
It is simple, simply that we could place the protocols that we accept and that versions such as 1.16.100, 1.16.200 and 1.16.201 can enter without problems

**Comment by Alemiz112** [comment]
Hello, waterdog supports every version since 1.8. Official repository is outdated, please use our new [forked repository](https://github.com/WaterdogPE/Waterdog).
For compiled JAR file, you following [link](https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterdog.jar).

**Comment by JuqnDeveloper** [comment]
Waterdog PE [MCPE]
