### ISSUE TITLE
Thank you and about to 2 question.

### ISSUE THREAD

**Issue by NycuRO** [yesdog/Waterdog#2]
Thank you for your intention for this project. By you, ProtocolSupport TCP or Bedrock Raknet is better?

Btw, you can add support for this?:

https://github.com/NukkitX/Network

https://github.com/NukkitX/Protocol

And plugin support exist? Documentary API?

And about project: This add support only for PE or add support for Java Edition and PE?

Btw i discovered some bugs:

1) On player list we have 2 names : https://imgur.com/a/dG8dzH5

2) proxy don't have xbox-auth support, and that means if you have on a nukkit/pmmp server xbox-auth turned on, we get kick: https://media.discordapp.net/attachments/437913371820687361/568383336284815367/unknown.png?width=1214&height=683

3) It works, yay! https://media.discordapp.net/attachments/437913371820687361/568383794181308426/unknown.png?width=1214&height=683

But if we disable raknet, we can't come to server, so players can enter to sections without problem :( *we need auth plugin, that means*

**Comment by colinrgodsey** [comment]
Ooh right, forgot Nukkit synapse protocol. I'll look into getting that added soon. Need to also add basic docs. You can still use the proxy for normal PC use, you just have to make 2 listeners (one with raknet: true, one with it false). As far as running nukkit in auth/online mode, that probably requires synapse protocol to function correctly. Otherwise we're unable to create our own 'mojang' signed auth bundle when connecting to the raw raknet protocol on an 'online' mode server.

- [ ] Nukkit synapse protocol
- [ ] Basic docs
- [ ] Player list shows own player twice (UUID rewrite probably needed)

**Comment by NycuRO** [comment]
By the way, we have natives? How to enable? I'm a PE user, not a PC.

**Comment by NycuRO** [comment]
And another by the way, protocol and network what i sended is from rewrite branch, will be better to use that instead of protocol what is used now on master

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/7eb8d116f5360aae3e69698738498fc3fe613c82
