### ISSUE TITLE
Proxy Bug

### ISSUE THREAD

**Issue by TimsLab** [yesdog/Waterdog#73]
Hey, if I join over the Proxy and you place or break blocks an random items come. 
https://prnt.sc/q2yq39
What is the issue can you help me?
Thanks!

**Comment by TimsLab** [comment]
I'am using Pocketmine 1.30

**Comment by CupidonSauce173** [comment]
I have the same exact issue. 
When interacting with a block or breaking it, it creates a kind of sphere of random items and when you leave / join back, the map is normal so I guess it's client side issue.
Without the proxy there is no bug and weirdly in a lobby server (with proxy) there is no issue. It happens when you go from lobby to another server but if you get back in the lobby, the bug doesn't appear. It's really only in other servers than lobby as I noticed.

**Comment by TimsLab** [comment]
the same thing happens to me too!

**Comment by Alemiz112** [comment]
Hi, we know about this problem already.
It is caused due to `block pallete randomization`. You have to create plugin that will disable randomization. It means you only need to make all pallets same. 

But if someone is doing `Nukkit <-> PMMP` transfers he has to make both pallets same (not just turn off randomization). You would have to import nukkit pallete into pmmp. Or import pmmp pallete into nukkit.

If you will exit this outdated plugin. It will work.
https://github.com/TobiasG-DE/RuntimeID-Fixer/blob/master/src/TobiasDev/RuntimeFixer.php

**Comment by TimsLab** [comment]
Ok thanks!
