### ISSUE TITLE
Pls Fixx Blockpalette 

### ISSUE THREAD

**Issue by Hajatoby** [yesdog/Waterdog#86]
**Version of Waterdog**
Waterdog-Bootstrap:1.15-SNAPSHOT:81eb6a5:300 by md_5

**Expected Behavior**
Nukkit has changed the block palette especially beetroot. The problem is that update blocks cause the world not to be ticketed

**Actual Behavior**

**Crashdump, Backtrace or Other Files**
no

**Describe the bug**
When you place seeds, bug them back and set as an update block. Shortly thereafter, the world can no longer be ticked

**To Reproduce**
Wenn man Samen platziert buggen sie zurück und setzen sich als Update Block. Kurz darauf kann die welt nicht mehr getickt werden

**Screenshots**
https://prnt.sc/qm0zjq

**Server software used:**
 Nukkit

**Additional context**
Please update to the latest build https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/redstone/

**Comment by RednedEpic** [comment]
To elaborate a bit more with information from the Nukkit Discord pertaining to this issue, the block palette in Nukkit was updated to be encoded in little endian instead of network, since it was causing issues in Nukkit itself. Unsure if this is where the issue lies, but I thought this might help a bit 😄.

**Comment by Alemiz112** [comment]
I but dont understand what do you mean  ``When you place seeds, bug them back and set as an update block. ``.

**Comment by Alemiz112** [comment]
Should be already fixed.
